### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by niahoo** [kodus/file-cache#5]
Hello,

Can you tell me how your implementation works ?

I see the following : 

```PHP

    public function get($key, $default = null)
    {
        ...

        $expires_at = @filemtime($path);

        if ($this->getTime() >= $expires_at) {
            @unlink($path); // file expired
        }
        ...
    }

    protected function getTime()
    {
        return time();
    }

```

As `filemtime()` returns the last modified time of the file, it is always a time in the past.
As `getTime()` returns `time()`, it is always the present time.
If the cache was set in the same second interval as it is read, both could be present, but you use `>=`.

To me, it means that whenever you read the cache, you start with deleting it. Am I missing something ? Can you help me to understand the code ?

Thank you.

**Comment by mindplay-dk** [comment]
I understand your confusion - the variable name `$expires_at` was supposed to clarify the fact that we're using the modification timestamp to indicate when cache-files expire.

As you can see from the following line, we futz the modification timestamp, so that it indicates the expiration time:

https://github.com/kodus/file-cache/blob/master/src/FileCache.php#L140

It's either that, or a separate file (or worse, a database) since there is nowhere else we can store the modification timestamp.

As I recall, we referenced this pattern from Symfony's file-cache.

It's a bit confusing, but it's quite efficient - and the tests prove that it works :-)

**Comment by niahoo** [comment]
Oh, I get it ! Thank you for the explanation, this will be useful too me.
